# Generated by Django 5.2.4 on 2025-07-11 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('last_updated', models.DateField(auto_now=True)),
                ('current_version', models.CharField(max_length=50)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='game_covers/')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='MemoryOffset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('offset', models.CharField(max_length=50)),
                ('offset_type', models.CharField(choices=[('float', 'Float'), ('int', 'Integer'), ('byte', 'Byte'), ('bool', 'Boolean'), ('string', 'String')], max_length=10)),
                ('version', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offsets', to='core.game')),
            ],
        ),
        migrations.CreateModel(
            name='Pointer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('pointer_path', models.TextField()),
                ('base_address', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointers', to='core.game')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('download_link', models.URLField(verbose_name='Trainer Download Link')),
                ('download_link_ce_xml', models.URLField(blank=True, help_text='Optional link to download Cheat Engine XML table', null=True, verbose_name='Cheat Engine XML Download Link')),
                ('features', models.TextField()),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainers', to='core.game')),
            ],
        ),
    ]
