# Generated by Django 5.2.4 on 2025-07-11 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_trainer_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='features',
            field=models.TextField(),
        ),
    ]
